import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create<any>({
  screen: {
    display: 'flex',
    backgroundColor: '#19191c',
    padding: 30,
    gap: 16,
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  viewStyles: (color: string) => ({
    width: '100%',
    border: `1px solid ${color}`,
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 6,
    padding: '10px',
    position: 'relative',
    gap: 8,
  }),
  badge: (color: string) => ({
    backgroundColor: color,
    color: '#000',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    border: '1px solid transparent',
    position: 'absolute',
    top: '-21px',
    left: '16px',
    height: '25px',
    padding: '8px',
    maxWidth: '90px',
    fontWeight: 700,
    zIndex: 6,
    borderRadius: 4,
  }),
  valueInfoStyles: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
  valueStyles: {
    display: 'flex',
    justifyContent: 'flex-end',
    fontSize: 12,
    opacity: 0.5,
    marginBottom: '5px',
  },
  nftListStyles: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    overflow: 'scroll',
  },
  imageStyles: {
    width: '50px',
    height: '50px',
  },
  buttonWrapperStyles: {
    display: 'flex',
    justifyContent: 'center',
  },
  borrowButtonStyles: (color: string) => ({
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    borderRadius: 7,
    backgroundColor: color,
    color: 'black',
    width: '100%',
  }),
  loansStatusStyles: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: '60px',
    textAlign: 'center',
    gap: '15px',
    paddingRight: 15,
    paddingLeft: 15,
  },
  text: {
    color: '#fff',
  },
  goBackButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 7,
    color: '#000',
    height: 40,
    width: 100,
    backgroundColor: '#9cff1f',
  },
})
